### ISSUE TITLE
Likely performance regressions because of cPickle -> pickle renames

### ISSUE THREAD

**Issue by mjuric** [RobertLuptonTheGood/eups#59]
@migueldvb: I just hit a bug (the fix is on d03df26c8747b9a44a8b0845e9124e0b79613ced) due to a change introduced in 65797ade8a53459f2dcfd358a17427473b0f7b3a, where `cPickle` imports were all changed to `pickle`. That made me notice the change (the bug was genuine).

I think a switch to `pickle` will cause problems for those running Python 2.7. We rely on pickling for reading and writing the product caches, both of which are already performance bottlenecks (i.e., we with stacks harboring thousands of versions, like the one on `lsst-dev`). Moving to `pickle` from `cPickle` will make it (much) worse.

This should be fixed, before we can make a 2.x release. Probably with something like `try import cPickle as pickle ... except ImportError: import pickle` stanzas in the few files where it appears?

**Comment by migueldvb** [comment]
Sorry about this regression. PR #57 has a commit that tries to import cPickle and otherwise imports pickle in those files that were modified for python 3 compatibility. This branch has conflicts with current master so I will open a new request with a single commit to fix this issue in the files that are affected by the problem.

**Comment by mjuric** [comment]
Ah, sorry, didn't notice #57 -- my mistake! #60 looks good, will merge it.
