### ISSUE TITLE
bugs in distrib sub-package

### ISSUE THREAD

**Issue by r-owen** [RobertLuptonTheGood/eups#72]
pyflakes has found a number of bugs in the distrib sub-package of eups (a package I missed when performing the cleanup on issue 66). These include:

- builder.py uses undefined variable `inVersion` (twice). I suspect `versionName` is wanted, instead.
- Distrib.py uses undefined symbol `system`
- Repositories.py uses undefined symbols `tag` (actually `tag.name` on line 216), `traceback` and `line`
- Repository.py uses undefined symbol `generic` on line 16; perhaps it should be `"generic"`
- server.py uses undefined function `addProduct`. Also, this line appears to be invalid python code (if it is valid then it is unclear):

    for versName in (inVersion, "any") or fnmatch.fnmatch(inVersion, versName):

the beginning of the for loop is fine, but I don't understand what "or fnmatch..." part is doing.

**Comment by mjuric** [comment]
Maybe the `fnmatch` line is RHL's Python brainteaser for job applicants ;-)?

I'd speculate that the intent of the `fnmatch` part was to allow wildcards in versions in `manifest.remap` files (e.g. see [https://github.com/RobertLuptonTheGood/eups/blob/master/python/eups/distrib/server.py#L1837](here)), but the effect of that clause is a no-op -- the in front of it has two elements (and is considered to be `True`), so the `fnmatch` part never executes (and if it tried to, it'd return `False`, which would cause an exception to be raised because it's not an iterable).

To restore the intended functionality, I think you'll want to add another if statement below that for loop, something like:
```
for (versName, mapping) in self._mapping[flavor][inProduct].items():
    if fnmatch.fnmatch(inVersion, versName):
        return mapping
```
(caveat: haven't tested the code above).

**Comment by timj** [comment]
Thank goodness. I spent 15 minutes experimenting in a python shell trying to work out how the second half of the `or` could ever execute anything and I couldn't get it to do anything.

**Comment by r-owen** [comment]
Thank you both. My strong preference is to omit the "or" clause, thus exactly preserving the current behavior while making the code easier to read and preserving the current behavior.

If wildcards are wanted I suggest that the code be added in a new ticket.
