### ISSUE TITLE
setup script fails with "setup not found"

### ISSUE THREAD

**Issue by r-owen** [RobertLuptonTheGood/eups#77]
A recent change to master seems to have broken eups for me. When I try to run the bash setup script I get:

    localhost$ setup
    -bash: setup: command not found

and neither setup nor eups commands are available. I discovered this after rebasing my fix for #75 to master, preparatory to merging. I'll look into it.

**Comment by r-owen** [comment]
The offending commit is f86f275 which simply changes ProductStack.py as follows:

     -        fd = utils.AtomicFile(file, "w")
    +        fd = utils.AtomicFile(file, "wb")

I don't know why this innocuous-looking commit would break my eups, but it does. Why was this change needed?

**Comment by migueldvb** [comment]
This was introduced for py3 support. I did not test it under python 2, sorry.

**Comment by r-owen** [comment]
Can I please take it out for now, until you come up with a fix that works under both?

**Comment by migueldvb** [comment]
Sure, please do that.

**Comment by r-owen** [comment]
Fixed using branch "fix77" that simply undoes that one simple commit

**Comment by timj** [comment]
`wb` mode is meant to work in Python 2 and 3 so this must be telling us there is some bytes vs string incompatibility somewhere.

**Comment by mjuric** [comment]
The problem is much simpler than that -- the breakage is due to me asserting on `== w` in here:

https://github.com/RobertLuptonTheGood/eups/blob/6d1d657bd3f77fdd3dd41034009a262b621d2f80/python/eups/utils.py#L832

and that should be changed to in `['w', 'wb']` and then change the line at https://github.com/RobertLuptonTheGood/eups/blob/6d1d657bd3f77fdd3dd41034009a262b621d2f80/python/eups/utils.py#L838 to use the `mode` variable instead of explicitly using `"w"`.

**Comment by migueldvb** [comment]
Thank you @mjuric for finding the solution to this problem. I will open a new pull request to include these changes.
